# Generated by Django 4.2.1 on 2023-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_tguser_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
