# Generated by Django 4.2.1 on 2023-05-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_tguser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
