# Generated by Django 4.2.1 on 2023-05-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_tguser_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
