# Generated by Django 4.2.1 on 2023-05-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_tguser_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_name',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
